name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Nuget
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Restore Nuget package
      run: nuget restore
    - name: MSBuild
      id: msbuild
      run: msbuild
      
