name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.3'
    - name: check ruby
      run: ruby -v
    - name: check bundler
      run: bundler -v

      
