name: CI

on: [push]

jobs:
  ubuntu-latest-ruby-default:
    name: "default ruby on ubuntu latest"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - name: check ruby
      run: ruby -v
    - name: check bundler
      run: bundler -v
    - name: install bundler
      run: gem install bundler
      
  ubuntu-1604-ruby-default:
    name: "default ruby on ubuntu 16.04"
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - name: check ruby
      run: ruby -v
    - name: check bundler
      run: bundler -v
    - name: install bundler
      run: gem install bundler

  osx-catalina-ruby-default:
    name: "default ruby on mojave"
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - name: check ruby
      run: ruby -v
    - name: check bundler
      run: bundler -v
    - name: install bundler
      run: gem install bundler
